#!/Users/mickey.winters/prog/lci/lci
HAI 1.4
  CAN HAS MANGO?
  VISIBLE "Content-Type: text/plain:)"

  I HAS A CLIENT ITZ MANGO IZ CONNEKTIN YR "mongodb://localhost:27017" MKAY
  I HAS A TODOS ITZ MANGO IZ COLEKTIN YR CLIENT AN YR "test" AN YR "TODOS" MKAY

  I HAS A MESG
  GIMMEH MESG

  VISIBLE MESG

KTHXBYE