#!/Users/mickey.winters/prog/lci/lci
HAI 1.4
  CAN HAS MANGO?
  VISIBLE "Content-Type: text/plain:)"

  I HAS A CLIENT ITZ MANGO IZ CONNEKTIN YR "mongodb://localhost:27017" MKAY
  I HAS A TODOS ITZ MANGO IZ COLEKTIN YR CLIENT AN YR "test" AN YR "TODOS" MKAY

  I HAS A FORM
  GIMMEH FORM

  I HAS A TEXT ITZ MANGO IZ PARSIN YR "text" AN YR FORM MKAY

  O HAI IM DOC
    I HAS A text ITZ TEXT
    I HAS A done ITZ FAIL
  KTHX

  MANGO IZ INSERTIN YR TODOS AN YR DOC MKAY

KTHXBYE